config/routes.rb
Rails.application.routes.draw do

  # devise_for user authentication URI
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  # root for index page URI
  root "books#index"

  # Resources for CRUD ability URI
  resources :books do
    resources :reviews
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  belongs_to :category
  has_many :reviews

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :title, presence: true
  validates :description, presence: true
  validates :author, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :books
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
  has_many :reviews

  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_book, only: [:show, :edit, :update, :destroy]

	def index
		if params[:category].blank?
			@books = Book.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@books = Book.where(:category_id => @category_id).order("created_at DESC")
		end
	end

	def show
		if @book.reviews.blank?
      @average_review = 0
    else
      @average_review = @book.reviews.average(:rating).round(2)
    end
	end

	def new
		@book = current_user.books.build
		@categories = Category.all.map{ |c| [c.name, c.id]  }
	end

	def create
		@book = current_user.books.build(book_params)
		@book.category_id = params[:category_id]

		if @book.save
			redirect_to @book, notice: "Awesome, you created new book!"
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		if @book.update(book_params)
			redirect_to @book, notice: "Make it better..."
		else
			render 'edit'
		end
	end

	def destroy
		@book.destroy
		redirect_to root_path
	end

	private
		def book_params
			params.require(:book).permit(:title, :description, :author, :user_id, :image, :category_id, :slug)
		end

		def find_book
			@book = Book.friendly.find(params[:id])
		end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_book
  before_action :find_review, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.book_id = @book.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to book_path(@book)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to book_path(@book)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to book_path(@book)
  end

  private
    def review_params
      params.require(:review).permit(:rating, :comment)
    end

    def find_book
      @book = Book.friendly.find(params[:book_id])
    end

    def find_review
      @review = Review.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
	<%= f.file_field :image %>
	<%= f.input :title, label: "Book Title" %>
	<%= f.input :description %>
	<%= f.input :author %>
	<%= f.button :submit, :class => 'btn-custom2' %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-book-form">

		<h1>Edit Book</h1>

		<%= simple_form_for @book, :html => { :multipart => true } do |f| %>
			<%= f.select :category_id, @categories %>
			<%= f.file_field :book_img %>
			<%= f.input :title, label: "Book Title" %>
			<%= f.input :description %>
			<%= f.input :author %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>

	</div>

</div>

app/views/books/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @books.count == 0 %>

	<h1>There are no books currently in this category</h1>

<% else %>

	<div class="row">

		<% @books.each do |book| %>

			<div class="col-md-3">
				<a href="/books/<%= book.id %>">
					<%= image_tag book.image.url(:medium), class: "book" %>
				</a>
			</div>

		<% end %>

	</div>

<% end %>

app/views/books/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-book-form">

		<h1>New Book</h1>

		<%= render 'form' %>

	</div>

</div>

app/views/books/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @book.image, class: "book-show" %>
  </div>

  <div class="col-md-8">
    <div class="book-info">
      <h2 class="book-title"><%= @book.title %></h2>
      <h3 class="book-author"><span>From</span> <%= @book.author %></h3>
      <h2 class="avg-rating">Average Rating</h2>
      <div class="average-review-rating" data-score=<%= @average_review %>></div><br>
      <span>Based on <%= @book.reviews.count %> reviews</span>
      <p class="book-desc"><%= @book.description %></p>
    </div>
  </div>
</div>

<br><br>

<div class="btn-group">
  <a href="<%= root_path %>" class="btn btn-default"><span class="glyphicon glyphicon-chevron-left">&nbsp;</span>Back</a>
  <a href="<%= new_book_review_path(@book) %>" class="btn btn-default"><span class="glyphicon glyphicon-pencil">&nbsp;</span>Add Review</a>
  <% if user_signed_in? %>
    <% if @book.user_id == current_user.id %>
      <a href="<%= edit_book_path(@book) %>" class="btn btn-default"><span class="glyphicon glyphicon-edit">&nbsp;</span>Edit Book</a>
      <%= link_to book_path(@book), class: "btn btn-default", method: :delete, data: {confirm: "Are you sure?"} do %>
        <span class="glyphicon glyphicon-trash">&nbsp;</span>Delete Book
      <% end %>
    <% end %>
  <% end %>
</div>

<br><br>

<div class="row reviews">
  <div class="col-md-4">
    <%= render @book.reviews %>
  </div>
</div>

<script type="text/javascript">
  $('.review-rating').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script type="text/javascript">
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function(){
      return $(this).attr('data-score')
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book Review</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= root_path %>">Book Review</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% Category.all.each do |category| %>
                  <li>
                    <%= link_to category.name, books_path(category: category.name), class: "link" %>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li><a href="<%= new_book_path %>"><span class="glyphicon glyphicon-pencil">&nbsp;</span>Add Book</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="<%= edit_user_registration_path %>"><span class="glyphicon glyphicon-user">&nbsp;</span>Settings</a></li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out">&nbsp;</span>Log Out
              <% end %>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav">
            <li><a href="<%= new_user_registration_path %>"><span class="glyphicon glyphicon-user">&nbsp;</span>Sign Up</a></li>
            <li><a href="<%= new_user_session_path %>"><span class="glyphicon glyphicon-log-in">&nbsp;</span>Login</a></li>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
       <div class="alert alert-info"><%= msg %></div>
     <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for([@book, @book.reviews.build]) do |f| %>
  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/_review.html.erb
<div class="review">
	<h3>Review</h3>
	<div class="review-rating" data-score="<%= review.rating %>"></div>
	<p class="review-comment"><%= review.comment %></p>
	<p><%= review.user.name %></p>

		<% if user_signed_in? %>

			<% if review.user_id == current_user.id %>

				<div class="links btn-group">

					<%= link_to "Edit", edit_book_review_path(review.book, review), class: "btn btn-custom" %>
					<%= link_to "Delete", book_review_path(review.book, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-custom" %>

				</div>
				<br><br>

			<% end %>

		<% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="edit-review-form">

		<h1>Edit Review</h1>

		<%= simple_form_for([@book, @review]) do |f| %>
			<div id="rating-form">
				<label>Rating</label>
			</div>
			<%= f.input :comment %>
			<%= f.button :submit, :class => "btn-custom2" %>
		<% end %>

	</div>

</div>

<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="col-md-6 col-md-offset-3">

	<div class="new-review-form">

		<h1>New Review</h1>

		<%= render 'form' %>

	</div>

</div>